### ISSUE TITLE
GCSF's full name

### ISSUE THREAD

**Issue by tehoko** [harababurel/gcsf#15]
Please add an explanation what "GCSF" stands for to the readme.

From [Hacker News](https://news.ycombinator.com/item?id=17436980):

> GCSF stands for "Google Conduce Sistem de Fișiere" -- a (bad) word-by-word Romanian translation of "Google Drive File System".

**Comment by rr-** [comment]
I noticed this issue as well, and since the project is still only 2 months young, I think there's still a window of opportunity to change the project name to something more intuitive, for example `gdfs` (Google Drive File System). It's worth mentioning that suffix `fs` is a de facto standard for all kind of file systems, including FUSE (`gocryptfs`, `gopherfs`, `avfs`, `btfs` etc. etc.)

**Comment by akhilerm** [comment]
[gdfs](https://github.com/robin-thomas/GDFS) is already there. Should be something else.

**Comment by UmutAlihan** [comment]
gdvfs -> Google Drive Virtual File System?

**Comment by harababurel** [comment]
I would like to continue using GCSF for the time being, unless a better alternative shows up.
