### ISSUE TITLE
Wrong disc usage

### ISSUE THREAD

**Issue by Nudin** [harababurel/gcsf#28]
On a mounted gcsf `du` shows wrong datasizes, this is due to the filesystem reporting 512 Bytes disc usages for every file (compare `ls -ls`).
For `du` this can be passed by with `--apparent-size`, but other programs rely on this information.

**Comment by harababurel** [comment]
I switched to using 512 bytes as the block size (see 7dcb48fa930dd89a4952f3c8c25540df94a5a46e). From my local tests, it seems that `du` now reports accurate sizes without having to provide `--apparent-size`.

There are still some sources of errors:
* Exportable files are reported as occupying 10 MB (Drive reports 0 bytes but you would see them as "empty file" if GCSF did this as well)
* Directories occupy one block each (512 bytes, most likely insignificant)
* The sizes reported by `df` might still be different from those reported by `du` because they also account for storage used by Gmail and Photos.

I'm closing the issue for now. Feel free to reopen if you still encounter wrong sizes.
