### ISSUE TITLE
google-drive3-fork

### ISSUE THREAD

**Issue by ignatenkobrain** [harababurel/gcsf#29]
Hey,

where could I find sources for this? Also any reason not to send patch to upstream?

**Comment by harababurel** [comment]
The fork is almost identical to the original [crate](https://crates.io/crates/google-drive3). The only difference is the addition of the [`doit_without_upload`](https://docs.rs/google-drive3-fork/1.0.10/google_drive3_fork/struct.FileUpdateCall.html#method.doit_without_upload) method for file updates. This is similar to [`upload`](https://docs.rs/google-drive3-fork/1.0.10/google_drive3_fork/struct.FileUpdateCall.html#method.upload) and [`upload_resumable`](https://docs.rs/google-drive3-fork/1.0.10/google_drive3_fork/struct.FileUpdateCall.html#method.upload_resumable) but allows the caller to change file metadata without changing the content as well.

I haven't sent a patch upstream because this is a very hacky fix for an issue that I encountered. The original crate is programmatically generated from a set of template files. A slightly better workaround is described in https://github.com/Byron/google-apis-rs/issues/191#issuecomment-404167471.

As the author [does not plan on continuing work on the project](https://github.com/Byron/google-apis-rs/issues/191#issuecomment-404212165) and the fix was good enough for the scope of this project, I haven't looked into it further.
