### ISSUE TITLE
Add mount command at the end of the ~/.profile file

### ISSUE THREAD

**Issue by cdknight** [harababurel/gcsf#37]
In order for users to be able to use this without manually mounting it, we need to add an entry to mount at the end of the ~/.profile file. This would make the program much more usable (by default).

**Comment by harababurel** [comment]
I don't think this is the best way to go about mounting the file system. Some users might prefer running it manually (inside a `tmux` or `screen` session). You might also want to return to the command later to check the logs. There is also the risk of running gcsf multiple times if you log in to different TTYs.

I would suggest creating a cron job that automatically mounts gcsf at every reboot. Something like this:

```shell
@reboot tmux new -s gcsf_session gcsf mount <mountpoint> -s <session_name>
```

And then verify that it works by attaching to the session: `tmux a -t gcsf_session`.
It might require some fiddling to get it to work. Maybe use `su -u <username>` in order to ensure that the command is run not by `cron` but by your own user.

**Comment by bexelbie** [comment]
Am I understanding correctly that the gcsf command doesn't become a daemon or otherwise exit?  Is the only/preferred unmount to Ctrl-C the process?

**Comment by harababurel** [comment]
That is correct. Either Ctrl-C the process or `fusermount -u $mountpoint` (which also kills the process)

**Comment by harababurel** [comment]
@cdknight: in 43143e0b92175116265bb7be955b6acdc369cc97 I added a systemd service configuration file which allows users to mount the file system as a system service, using `systemctl start gcsf`.

You can also run `systemctl enable gcsf` in order to mount the filesystem automatically at boot time. Logs can be inspected using `journalctl -u gcsf`.

Just copy the service file to `/etc/systemd/system/gcsf.service` and edit it with the corresponding variables. `sudo systemctl daemon-reload && sudo systemctl start gcsf` should then work.

**Comment by arifzeeshan** [comment]
> Just copy the service file to `/etc/systemd/system/gcsf.service` and edit it with the corresponding variables. `sudo systemctl daemon-reload && sudo systemctl start gcsf` should then work.

It looks for the gcsf config in the root user. I am getting the following error. 

`ERROR gcsf > Token file "/root/.config/gcsf/arif" does not exist.
 ERROR gcsf > Try logging in first using ``gcsf login.``
 fusermount[24614]: /usr/bin/fusermount: failed to unmount /home/arif/imearifkhan@gmail.com: Invalid argument
gcsf.service: Control process exited, code=exited, status=1/FAILURE
`

**Comment by harababurel** [comment]
510430e should fix this. Add `User=...` in `gcsf.service` and it should run GCSF as your own user even if you start the service as root.
