### ISSUE TITLE
Update gcsf

### ISSUE THREAD

**Issue by UmutAlihan** [harababurel/gcsf#40]
How can we update our current gcsf?

I see many new commits in this repo.

Should we compile it all over again to have the recent improvements?

Sorry I am noob btw

**Comment by harababurel** [comment]
Unfortunately I haven't had time lately to contribute much to the project. The recent commits are mostly small changes (e.g. fixing code formatting so that `rustfmt` doesn't break the build).

I will create a new version this week and push it to crates.io. This way you can run `cargo install gcsf` (possibly with `--force`) and it will update to the latest version, so you don't have to build the project manually.
