### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by penguinunix** [harababurel/gcsf#75]
Hi,

Trying gcsf login session and open the browser but got this message:

Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.

Is there any fix for that?

**Comment by mxdpeep** [comment]
this project is dead - let's move on

*Filip Oščádal*
*https://fred.mxd.cz <https://fred.mxd.cz/>*

**Comment by ignatenkobrain** [comment]
@harababurel is it really dead?

**Comment by JonLeeCon** [comment]
Well dead or not [I just submitted a PR](https://github.com/harababurel/gcsf/pull/76) so that you can use your own Google OAuth client secrets.

1. Go to [https://console.developers.google.com](https://console.developers.google.com) and create a project if you do not already have one
2. Enable Google Drive APIs
3. Go to credentials and click _create credentials_>_help me choose_. Select the _Google Drive API_, _Other UI (e.g. Windows, CLI tool)_, and _User data_ options

Use those credentials in the new config field from the PR

**Comment by AlexWayfer** [comment]
@JonLeeCon Thank you!

**Comment by ddonindia** [comment]
@JonLeeCon  Thanks this worked for me too.

**Comment by DAC324** [comment]
> Well dead or not [I just submitted a PR](https://github.com/harababurel/gcsf/pull/76) so that you can use your own Google OAuth client secrets.
> 
> 1. Go to https://console.developers.google.com and create a project if you do not already have one
> 2. Enable Google Drive APIs
> 3. Go to credentials and click _create credentials_>_help me choose_. Select the _Google Drive API_, _Other UI (e.g. Windows, CLI tool)_, and _User data_ options
> 

Did all that but I am stuck at this step:

> Use those credentials in the new config field from the PR

What am I supposed to do? To explain, I have installed GCSF from AUR (https://aur.archlinux.org/packages/gcsf-git/)

**Comment by ayoubelmhamdi** [comment]
Look for file called `~/.config/gcsf/gcsf.toml` and search for `client_secrect=...` at the end for file.


![image](https://user-images.githubusercontent.com/34358145/197359929-779888f3-b666-425b-b41f-74a5f5576797.png)
